## Q1. What are the three measures of central tendency?

Mean 
Medain
Mode

## Q2. What is the difference between the mean, median, and mode? How are they used to measure the central tendency of a dataset?

In [3]:
import seaborn as sn
dftip = sn.load_dataset("tips")
dftip.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
dftip.shape

(244, 7)

In [9]:
dftip.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

The mean, median, and mode are all measures of central tendency, which is a way to describe the center or typical value within a dataset. Here’s what each of them represents and how they differ:

### Mean
The mean, often referred to as the average, is calculated by adding all the numbers in a dataset and then dividing by the count of those numbers. It is the arithmetic average and is affected by outliers and skewed distributions.

**Formula for Mean:**
\[ \text{Mean} = \frac{\sum_{i=1}^{n} x_i}{n} \]
where \( x_i \) represents each number in the dataset and \( n \) is the number of observations.

### Median
The median is the middle value in a dataset when it is ordered from least to greatest. If there is an even number of observations, the median is the average of the two middle numbers. The median is not affected by outliers or skewed distributions, making it a better measure of central tendency for such datasets.

**Finding the Median:**
- Order the data from least to greatest.
- If \( n \) is odd, the median is the value at position ( n+1/2 ).
- If \( n \) is even, the median is the average of the values at positions (n/2 ) and ( n/2 + 1 ).

### Mode
The mode is the number that appears most frequently in a dataset. There can be more than one mode if multiple numbers appear with the same highest frequency, in which case the dataset is called multimodal. If no number repeats, the dataset is considered to have no mode. The mode is useful for categorical data where we wish to know which is the most common category.

### Usage in Measuring Central Tendency
- **Mean**: Provides a useful measure of central tendency when dealing with numeric data that is symmetrically distributed without outliers.
- **Median**: More representative of the central tendency in skewed distributions or when the data contains outliers, as it is not affected by extreme values.
- **Mode**: Used when the most common item, category, or value in a dataset is desired. It is the only measure of central tendency that can be used with nominal data.

### Example
Consider the following dataset of the number of pets owned by a group of people: {0, 0, 1, 1, 1, 2, 3, 4}

- **Mean**: (0 + 0 + 1 + 1 + 1 + 2 + 3 + 4) / 8 = 1.5
- **Median**: The middle values are 1 and 1 (since there are 8 numbers, an even count), so the median is (1 + 1) / 2 = 1.
- **Mode**: The value 1 appears most frequently, so the mode is 1.

### Conclusion
In conclusion, the mean, median, and mode are all valid measures of central tendency but are chosen based on the nature of the dataset and the specific requirements of the analysis. The mean is sensitive to every data point in the dataset, the median is resistant to extreme values, and the mode is concerned with frequency of occurrence.

## Q3. Measure the three measures of central tendency for the given height data:
## [178,177,176,177,178.2,178,175,179,180,175,178.9,176.2,177,172.5,178,176.5]

In [15]:
import pandas as pd
series = pd.Series([178,177,176,177,178.2,178,175,179,180,175,178.9,176.2,177,172.5,178,176.5])
series.describe()
## refer ony mean,50% and max


count     16.000000
mean     177.018750
std        1.847239
min      172.500000
25%      176.150000
50%      177.000000
75%      178.050000
max      180.000000
dtype: float64

In [14]:
Mean =  series.sum()/len(series)

177.01875

In [21]:
import numpy as np
# Dataset provided by the user
data = [178, 177, 176, 177, 178.2, 178, 175, 179, 180, 175, 178.9, 176.2, 177, 172.5, 178, 176.5]

# Calculating the median
median_value = np.median(data)
median_value

177.0



1. **Sort the Data**: Arrange the data points in ascending order.
2. **Determine the Middle Point**: Since there are 16 data points, an even number, the median will be the average of the 8th and 9th values in the sorted list.

For the given dataset: [178, 177, 176, 177, 178.2, 178, 175, 179, 180, 175, 178.9, 176.2, 177, 172.5, 178, 176.5]

Sorted: [172.5, 175, 175, 176, 176.2, 176.5, 177, 177, 177, 178, 178, 178, 178.2, 178.9, 179, 180]

The 8th and 9th values are both 177, so the median is 177.

You can easily do this calculation using a calculator or a spreadsheet program like Microsoft Excel or Google Sheets by using the MEDIAN function. If you'd like to attempt this again when the system is functioning, or if you have access to Python or another programming environment, you can use the `median` function from the statistics library or NumPy library to calculate it directly.

## Calculate the mode manually, you would follow these steps:

1. **List the Data**: Write down the numbers from the dataset.
2. **Count Frequency**: Count how many times each number appears.
3. **Determine the Most Frequent**: The number that appears most frequently is the mode.

For your dataset: [178, 177, 176, 177, 178.2, 178, 175, 179, 180, 175, 178.9, 176.2, 177, 172.5, 178, 176.5]

The mode can be found by counting each number:
- 175 appears twice,
- 176 appears once,
- 176.2 appears once,
- 176.5 appears once,
- 177 appears three times,
- 178 appears three times,
- 178.2 appears once,
- 178.9 appears once,
- 179 appears once,
- 180 appears once,
- 172.5 appears once.

Here, both 177 and 178 appear three times, which are the highest frequencies in the dataset, making them both modes. This means the dataset is bimodal.

In a computational environment, you could use the `mode` function from Python's statistics library, or the `stats.mode` function from the SciPy library, which would return the smallest of the modes in case of a multimodal dataset. If you have access to such tools, you can use them to verify this result.

In [24]:
from scipy import stats as st
modeValue = st.mode(data)
modeValue


ModeResult(mode=177.0, count=3)

## Q4. Find the standard deviation for the given data:
## [178,177,176,177,178.2,178,175,179,180,175,178.9,176.2,177,172.5,178,176.5]

In [26]:
data = [178,177,176,177,178.2,178,175,179,180,175,178.9,176.2,177,172.5,178,176.5]
stdValue = np.std(data)
stdValue

1.7885814036548633

## Calcuate standard deviation

1. **Calculate the Mean**: Add all the numbers together and divide by the count.
2. **Subtract the Mean and Square the Result**: For each number, subtract the mean and square the result (the squared difference).
3. **Find the Mean of Those Squared Differences**.
4. **Take the Square Root of that**: This gives you the standard deviation.

For your dataset, here are the steps:

Mean = (178 + 177 + 176 + 177 + 178.2 + 178 + 175 + 179 + 180 + 175 + 178.9 + 176.2 + 177 + 172.5 + 178 + 176.5) / 16

Then for each number: (number - mean)², sum all those squared differences.

Divide by (count - 1) if you're calculating sample standard deviation or by count for population standard deviation.

Take the square root of that quotient to get the standard deviation.

Using a calculator or a spreadsheet tool (like Excel or Google Sheets), you can apply these calculations step by step. In Excel, for instance, you could use the `STDEV.S` function for a sample standard deviation, which appears to be what you need here.

When the computational tools are back up, you can also use the `np.std()` function from the NumPy library with `ddof=1` to get the sample standard deviation, or simply use `pd.Series(data).std()` if you're using pandas.

## Q5. How are measures of dispersion such as range, variance, and standard deviation used to describe
## the spread of a dataset? Provide an example.

Measures of dispersion are statistical tools that describe the spread or variability within a dataset. They give you an idea of how much the data points differ from each other and from the central tendency (mean, median, mode). Here are the main measures of dispersion:

### Range
- **Definition**: The range is the simplest measure of dispersion and is calculated as the difference between the maximum and minimum values in a dataset.
- **Usage**: It gives a quick sense of the width of the distribution but is highly sensitive to outliers because it only considers the two extreme values.

### Variance
- **Definition**: Variance measures how far each number in the set is from the mean and thus from every other number in the set. It's calculated as the average of the squared differences from the Mean.
- **Usage**: Variance provides a more comprehensive measure of spread because it takes into account all data points. However, since it's squared, it's not in the same units as the data and can be difficult to interpret on its own.

### Standard Deviation
- **Definition**: Standard deviation is the square root of the variance and provides a measure of spread that is in the same units as the data.
- **Usage**: It is one of the most useful and widely used measures of dispersion because it reflects the dispersion around the mean and allows for direct comparison with the data points.

### Example

Imagine a dataset representing the test scores of a class: [70, 80, 80, 82, 88, 90]

- **Range**: \( 90 - 70 = 20 \) points
- **Variance**: Calculate the mean (82), then for each score, subtract the mean and square the result, and finally average those squared differences.
- **Standard Deviation**: Take the square root of the variance.

Let's calculate these using Python:

```python
import numpy as np

scores = np.array([70, 80, 80, 82, 88, 90])
mean_score = np.mean(scores)
range_score = np.ptp(scores)  # Peak-to-peak is another term for range
variance_score = np.var(scores, ddof=1)  # Sample variance
std_deviation_score = np.sqrt(variance_score)

print("Mean:", mean_score)
print("Range:", range_score)
print("Variance:", variance_score)
print("Standard Deviation:", std_deviation_score)
```

Assuming the computational tool were working, the code would output the mean, range, variance, and standard deviation of the test scores. This would provide an understanding of not only the average performance (mean) but also how spread out the scores are from the average (standard deviation) and from each other (range).

In [27]:
import numpy as np

scores = np.array([70, 80, 80, 82, 88, 90])
mean_score = np.mean(scores)
range_score = np.ptp(scores)  # Peak-to-peak is another term for range
variance_score = np.var(scores, ddof=1)  # Sample variance
std_deviation_score = np.sqrt(variance_score)

print("Mean:", mean_score)
print("Range:", range_score)
print("Variance:", variance_score)
print("Standard Deviation:", std_deviation_score)

Mean: 81.66666666666667
Range: 20
Variance: 50.26666666666667
Standard Deviation: 7.0898989179442236


## Q6. What is a Venn diagram?

A typical Venn diagram consists of overlapping circles, each representing a set. The areas where the circles overlap indicate the elements that belong to both sets, while the non-overlapping portions of the circles represent elements unique to each set. The size of the circles and their positions relative to each other can vary based on the specific information being conveyed.

Key features of a Venn diagram:

1. Intersection: The overlapping regions of the circles represent the elements that are common to the sets involved. These elements satisfy the criteria of both sets.

2. Union: The entire area covered by all the circles combined represents the union of all the sets, including all elements from all sets.

3. Disjoint sets: If two circles do not overlap at all, it means the sets have no elements in common, and they are said to be disjoint or mutually exclusive.

Venn diagrams are a helpful tool for visually illustrating relationships and comparisons between different sets or categories. They are often used in various fields, including mathematics (set theory), statistics (probability theory), logic (syllogisms), biology (genetics), and data analysis, to name a few. Venn diagrams can make complex relationships more understandable and are a valuable tool for problem-solving and data visualization.

## Q7. For the two given sets A = (2,3,4,5,6,7) & B = (0,2,6,8,10). Find:
## i) A B
## (ii) A ⋃ B

To find the intersection (A ∩ B) and the union (A ∪ B) of the two sets A and B, you can follow these steps:

(i) Intersection (A ∩ B):
   The intersection of two sets contains the elements that are common to both sets. In this case, you need to find the elements that are present in both sets A and B.

   A = {2, 3, 4, 5, 6, 7}
   B = {0, 2, 6, 8, 10}

   The elements that are common to both sets A and B are 2 and 6.

   A ∩ B = {2, 6}

(ii) Union (A ∪ B):
   The union of two sets contains all the unique elements from both sets, without duplicates.

   A = {2, 3, 4, 5, 6, 7}
   B = {0, 2, 6, 8, 10}

   Combine all the elements from both sets:

   A ∪ B = {0, 2, 3, 4, 5, 6, 7, 8, 10}

So, the answers are:
(i) A ∩ B = {2, 6}
(ii) A ∪ B = {0, 2, 3, 4, 5, 6, 7, 8, 10}

## Q8. What do you understand about skewness in data?

Skewness is a measure of the asymmetry of the probability distribution of a real-valued random variable about its mean. In simpler terms, skewness tells us about the direction and relative magnitude of a dataset’s deviation from the normal distribution. Here are key points about skewness:

### Types of Skewness:

- **Positive Skew (Right-Skewed)**: When the tail on the right side of the distribution is longer or fatter than the left side. In a positively skewed distribution, the mean and median will be greater than the mode (Mean > Median > Mode).
- **Negative Skew (Left-Skewed)**: When the tail on the left side of the distribution is longer or fatter than the right side. In a negatively skewed distribution, the mean and median will be less than the mode (Mean < Median < Mode).
- **Zero Skew (Symmetric)**: When the values are distributed symmetrically around the mean. This implies that the distribution looks the same to the left and right of the center point.

### Implications of Skewness:

- **Influence on Data Analysis**: Skewness can affect various statistical analyses since many statistical tests assume normal distribution (zero skewness). For instance, significant skewness may affect the validity of certain statistical tests.
- **Decision Making**: Understanding skewness is important for making decisions based on data. For example, if data about household income is positively skewed (which is typically the case), using the mean as an average may be misleading since it's higher than most people's incomes due to the influence of very high incomes.
- **Data Transformation**: Sometimes data is transformed (e.g., using log transformation) to reduce skewness and make the data more closely approximate a normal distribution, which is often a requirement for parametric statistical tests.

### Measuring Skewness:

Skewness is typically measured with Pearson’s first coefficient of skewness (mode-based) or the second coefficient of skewness (mean-based, which is more common).

The formula for the second coefficient of skewness is:

Skewness = 3(Mean - Median)/Standard Deviation 

or a more complex formula involving the third moment about the mean:

Skewness = E[(X - \mu)^3]}/sigma^3

where \( X \) is the random variable, \( \mu \) is the mean of \( X \), and \( \sigma \) is the standard deviation of \( X \).

### Example:

Consider an income dataset for a region: [25k, 30k, 35k, 40k, 50k, 55k, 60k, 200k]. The large value at the end (200k) will pull the mean up more than the median or mode, resulting in a positively skewed distribution. Most people's income will be below the average due to this skew.

Skewness is a fundamental concept in descriptive statistics and is critical for data analysis, particularly in the fields of finance, research, and any domain where data distribution plays a crucial role in decision-making.

Certainly! Let's simplify the concept of skewness.

Imagine you have a line of people arranged by height, so that the shortest person is at the start of the line and the tallest at the end. If most people are of average height, with just a few tall people, the line might stretch out longer on the tall end. If this were a graph, it would lean towards the shorter people with a long tail stretching out towards the taller people. This is what we call a "skewed" distribution.

Skewness tells us if there are more values on the high end or the low end of our dataset:

- **Positive Skewness**: This is like having the line of people with a few really tall individuals at the end. In a graph, most of the data would be piled up on the left side, with the "tail" stretching out to the right. In everyday terms, if you're looking at incomes, a positive skew means there are a few people with very high incomes raising the average.
  
- **Negative Skewness**: This would be like having a few very short individuals at the start of our line. On a graph, the tail would stretch out to the left. If this were a test where most people scored high, with a few low scores pulling the average down, that's a negative skew.

- **No Skewness**: If almost everyone is around the average height, with fewer short and tall people, the line of people would be quite even. On a graph, it would look symmetrical, with no tail longer on one side than the other.

Skewness is important because it can tell us if the average (mean) of our data might be thrown off by exceptionally high or low values. If there's a lot of skewness, we might want to use the median (the middle value when all are sorted) instead of the mean, because it gives us a better idea of what's typical for our dataset.